### ISSUE TITLE
The spelling is not correct of gifts

### ISSUE THREAD

**Issue by sudhanshu0603** [stores-cedcommerce/Internal--Shaka-Store-Built-Redesign---12-April22#1]
**Actual result:**
The spelling is not correct for gifts
![image](https://user-images.githubusercontent.com/102131636/162147823-299fb784-561d-4e54-8743-e3709469aaa5.png)

**Expected result:**
The spelling of gifts have to be correct.

**Comment by ui-abhishekkushwaha** [comment]
DONE

**Comment by sudhanshu0603** [comment]
ok, resolved
