### ISSUE TITLE
Count on the wishlist icon the header is not increasing.

### ISSUE THREAD

**Issue by sudhanshu0603** [stores-cedcommerce/Internal--Shaka-Store-Built-Redesign---12-April22#10]
**Actual result:** 
When we click on the header wishlist icon then the count is not coming for the added product on the header.
![image](https://user-images.githubusercontent.com/102131636/162167391-f66d3c7a-b12c-424e-8858-03ba155af9c7.png)

**Expected result:**
The count have to be visible on the wishlist icon on the header

**Comment by devAlokTripathi** [comment]
@sudhanshu0603  please check its already working .

**Comment by sudhanshu0603** [comment]
ok resolved
