### ISSUE TITLE
The section below the main banner, we can add the titles for the collection it will be much better.

### ISSUE THREAD

**Issue by sudhanshu0603** [stores-cedcommerce/Internal--Shaka-Store-Built-Redesign---12-April22#11]
**Actual result:** 
The section below the main banner, we can add the titles for the collection it will be much better.
![image](https://user-images.githubusercontent.com/102131636/162170571-47b13290-2739-4e98-958c-af4d0e91ebf9.png)

**Expected result:** 
we can add the title it will be much better. ( Suggestion )

**Comment by devAlokTripathi** [comment]
![image](https://user-images.githubusercontent.com/100207984/162314646-1ce0bc50-1955-406a-8c45-080160fea4fb.png)

**Comment by ui-abhishekkushwaha** [comment]
Not there is not need to add this customer self understood which collection they select easily in his requirement.
@devAlokTripathi i am removing this

**Comment by sudhanshu0603** [comment]
ok,
