### ISSUE TITLE
The zero price product is added.

### ISSUE THREAD

**Issue by sudhanshu0603** [stores-cedcommerce/Internal--Shaka-Store-Built-Redesign---12-April22#12]
**The url:** 
https://maszlcustombaskets.com/collections/brownies

**Actual result:** 
The price of the product is coming zero.
![image](https://user-images.githubusercontent.com/102131636/162171825-0de26380-d213-4f81-842b-d756b730bc5a.png)
**Expected result:**
The price of the product should not be zero.

**Comment by devAlokTripathi** [comment]
@sudhanshu0603  it is a test product but i will update the price please check 
![image](https://user-images.githubusercontent.com/100207984/162251223-52501b91-ff4e-4714-937e-112b8e1d8139.png)

**Comment by ui-abhishekkushwaha** [comment]
I had remove the tested product.

**Comment by sudhanshu0603** [comment]
ok, resolved
