### ISSUE TITLE
We can add the mobile number if client has given in the footer section.

### ISSUE THREAD

**Issue by sudhanshu0603** [stores-cedcommerce/Internal--Shaka-Store-Built-Redesign---12-April22#13]
**Actual result:**
We can add the mobile number if client has given in the footer section.
![image](https://user-images.githubusercontent.com/102131636/162173661-05bd83d4-6af7-4fda-995c-0faf1c5af910.png)
**Expected result:**
We can add mobile number if client has given .( Suggestion )

**Comment by devAlokTripathi** [comment]
@sudhanshu0603  not required. discuss with @Gyanendraky

**Comment by sudhanshu0603** [comment]
ok, resolved
