### ISSUE TITLE
In product page when we click on the main image then header is overlapping.

### ISSUE THREAD

**Issue by sudhanshu0603** [stores-cedcommerce/Internal--Shaka-Store-Built-Redesign---12-April22#15]
**Actual result:** 
In product page when we click on the main image then header is overlapping.
![image](https://user-images.githubusercontent.com/102131636/162176076-e078489b-97ba-43f8-bf06-3eea54a633ab.png)

**Expected result:** 
The header should not overlapp with the main image.

**Comment by devAlokTripathi** [comment]
@ui-abhishekkushwaha  bhai please check it . @sudhanshu0603  please review .

**Comment by ui-abhishekkushwaha** [comment]
Done please check

**Comment by sudhanshu0603** [comment]
ok, resolved
