### ISSUE TITLE
product page, the quantity input field is coming blank.

### ISSUE THREAD

**Issue by sudhanshu0603** [stores-cedcommerce/Internal--Shaka-Store-Built-Redesign---12-April22#16]
**Actual result:** 
1: product page, the quantity input field is coming blank.
2: The border is coming when we click on the input field then the border is coming it .( suggestion )
![image](https://user-images.githubusercontent.com/102131636/162177410-9fb45783-2fbd-491c-b15f-8ea76d9de28b.png)

![image](https://user-images.githubusercontent.com/102131636/162177613-115878de-ca91-4eaa-8da8-b839b306edd8.png)

**Expected result:** 
The empty input field is coming when we deleting the quantity.

**Comment by devAlokTripathi** [comment]
@sudhanshu0603  please check 
![image](https://user-images.githubusercontent.com/100207984/162283618-e24e894a-eb65-441a-ac14-0c0770a06f1e.png)

**Comment by sudhanshu0603** [comment]
ok, resolved
