### ISSUE TITLE
You may also like section when we hover over the product then the wishlist is not coming.

### ISSUE THREAD

**Issue by sudhanshu0603** [stores-cedcommerce/Internal--Shaka-Store-Built-Redesign---12-April22#17]
**Actual result:** 
You may also like section when we hover over the product then the wishlist is not coming.
![image](https://user-images.githubusercontent.com/102131636/162178309-f564d32a-33e8-46a7-87fe-ba47c6cb71f6.png)

**Expected result:** 
The wishlist have to come over the product on this section.

**Comment by devAlokTripathi** [comment]
@sudhanshu0603 
![image](https://user-images.githubusercontent.com/100207984/162276781-77f69518-ea4e-4c87-8a53-295fdfade388.png)
resolved please check .

**Comment by sudhanshu0603** [comment]
ok, resolved
