### ISSUE TITLE
the spelling can be Contact us it will be much better in the header and also in form of contact us

### ISSUE THREAD

**Issue by sudhanshu0603** [stores-cedcommerce/Internal--Shaka-Store-Built-Redesign---12-April22#18]
**Actual result:** 
the spelling can be Contact us it will be much better in the header. 
![image](https://user-images.githubusercontent.com/102131636/162179380-5583b801-a856-4929-a994-786c2fd4e9ad.png)

**Expected result:** 
The word for the contact should be like Contact us, it will be much better.(  Suggestion )
--------------------------------------------------------------------------------------------------------------------------------------------
**RETESTING :**
**Actual result:** 
When we will click on the contact us the form will open and there spelling is not correct.
![image](https://user-images.githubusercontent.com/102131636/162367628-86e4518d-8dd0-4e3c-b524-cbceb0a3f343.png)

**Expected result:**
The Spelling of the title of contact us have to be there it will be much better.

**Comment by devAlokTripathi** [comment]
@sudhanshu0603 
![image](https://user-images.githubusercontent.com/100207984/162274068-034a9f20-09b5-421c-8633-3caa73a4e364.png)

**Comment by sudhanshu0603** [comment]
ok, resolved
