### ISSUE TITLE
When we click on the quantity input field then the border is coming on it and it will come over the  - and + icon . ( Cart page ) )

### ISSUE THREAD

**Issue by sudhanshu0603** [stores-cedcommerce/Internal--Shaka-Store-Built-Redesign---12-April22#19]
**Actual result:** 
When we click on the quantity input field then the border is coming on it and it will come over the  - and + icon . 
![image](https://user-images.githubusercontent.com/102131636/162180757-ca4998be-5ac3-4d46-bc10-25382aa75b4f.png)

**Expected result:** 
If the border should not come it will be much better. ( suggestion )

**Comment by devAlokTripathi** [comment]
@sudhanshu0603  not required.

**Comment by sudhanshu0603** [comment]
ok
