### ISSUE TITLE
Collection page after applying filter option then the wishlist is disappearing.

### ISSUE THREAD

**Issue by sudhanshu0603** [stores-cedcommerce/Internal--Shaka-Store-Built-Redesign---12-April22#2]
**Actual result:** 
The wishlist is disappearing after applying filter.
![image](https://user-images.githubusercontent.com/102131636/162148265-5a960cf8-8c10-42e5-bbd2-ff28a1dc3ed6.png)

**Expected result:**
The wishlist icon have to come on applying the filter.
|
![image](https://user-images.githubusercontent.com/102131636/162148516-21b58ff2-8ade-4d07-9a8a-7b58918002f7.png)

**Comment by devAlokTripathi** [comment]
@sudhanshu0603  please check it is already fixed. please check this theme :
 RECENT BACKUP(CED_WORK_ON_THIS) + wishlist hero

**Comment by sudhanshu0603** [comment]
ok resolved
