### ISSUE TITLE
We can add the currency converter, language converter and chatbot .

### ISSUE THREAD

**Issue by sudhanshu0603** [stores-cedcommerce/Internal--Shaka-Store-Built-Redesign---12-April22#20]
**Actual result:** 
We can add the currency converter, language converter and chatbot.
**Expected result:**
We can add the currency converter, language converter and chatbot, if client wants. ( suggestion )

**Comment by devAlokTripathi** [comment]
@sudhanshu0603  already added when store is live then it reflects.

**Comment by devAlokTripathi** [comment]
![image](https://user-images.githubusercontent.com/100207984/162271364-18c58806-ce6f-45d5-ac88-8f53a0229ec3.png)

**Comment by sudhanshu0603** [comment]
ok,
