### ISSUE TITLE
The accordions are not used for the footer section

### ISSUE THREAD

**Issue by sudhanshu0603** [stores-cedcommerce/Internal--Shaka-Store-Built-Redesign---12-April22#21]
**Actual result:**
The accordions are not used for the footer section. 
![image](https://user-images.githubusercontent.com/102131636/162185079-23dee238-78bb-4372-89df-fc005f7afef1.png)

**Expected result:** 
The accordions have to be used for the footer it will be much better.
------------------------------------------------------------------------------------------------------------------------------------------
**RETESTING :**
**Actual result:** 
When we click on all the accordion then all the accordions are opening.
![image](https://user-images.githubusercontent.com/102131636/162366999-d3f0f4e8-44f9-41e4-8bf0-ff35d7aa6e45.png)

**Expected result:** 
Once we click on another accordion then the previous accordion have to be closed it will be much better.

**Comment by devAlokTripathi** [comment]
@sudhanshu0603 resolved please check
![image](https://user-images.githubusercontent.com/100207984/162265135-5f5c9af2-de84-431f-9dfe-92efbed158b7.png)
@ui-abhishekkushwaha bhai please check heading backgorund color.

**Comment by sudhanshu0603** [comment]
@devAlokTripathi , please review the retesting point.

**Comment by sudhanshu0603** [comment]
ok, resolved
