### ISSUE TITLE
Privacy policy in the footer page the horizontal scrolling is coming

### ISSUE THREAD

**Issue by sudhanshu0603** [stores-cedcommerce/Internal--Shaka-Store-Built-Redesign---12-April22#22]
**Actual result :**
Privacy policy in the footer page the horizontal scrolling is coming
![image](https://user-images.githubusercontent.com/102131636/162186778-78a5c94c-3135-40f2-921d-573a3538e650.png)

**Expected result:**
There should not be any horizontal scrolling inside the privacy policy page.

**Comment by ui-abhishekkushwaha** [comment]
Issue Fixed

**Comment by sudhanshu0603** [comment]
ok resolved
