### ISSUE TITLE
When we click on the contact detail accordion then the logo of footer is coming very big.

### ISSUE THREAD

**Issue by sudhanshu0603** [stores-cedcommerce/Internal--Shaka-Store-Built-Redesign---12-April22#23]
**Actual result:** 
When we click on the contact detail accordion then the logo of footer is coming very big.
![image](https://user-images.githubusercontent.com/102131636/162187642-e8b99444-3d26-4c54-936c-7f50c72345d7.png)
**Expected result:** 
The logo have to be of standard size.
------------------------------------------------------------------------------------------------------------------------------------------
**Retesting:**
**Actual result:** 
When we click on the text contact details in the footer then the address and email is moving up and down.
The video issue: https://www.awesomescreenshot.com/video/8301059?key=6ba5bc609fc5c557aae2cd04a85d3167
**Expected result:** 
The address and the email have to be on its fixed position, it will be much better.

--------------------------------------------------------------------------------------------------------------------------------------------
**againRetesting:**
**Actual result:**
1: The accordion is coming for the newsletter.
2: The accordion are not opening.
![image](https://user-images.githubusercontent.com/102131636/162557441-98e145b2-6627-42c8-b478-c299b5b1c59c.png)

**Expected result:**
1: The accordion have to work properly.
2: No need of accordion for the newsletter.

**Comment by sudhanshu0603** [comment]
Please review the retesting point added

**Comment by ui-abhishekkushwaha** [comment]
@devAlokTripathi please check this accordions issue and fixed it

**Comment by devAlokTripathi** [comment]
@sudhanshu0603  please check issued resolved.

**Comment by sudhanshu0603** [comment]
ok, resolved.
