### ISSUE TITLE
The text of the banners are not visible properly for ipad view, 

### ISSUE THREAD

**Issue by sudhanshu0603** [stores-cedcommerce/Internal--Shaka-Store-Built-Redesign---12-April22#24]
**Actual result:**
The text of the banners are not visible properly for ipad view, 
![image](https://user-images.githubusercontent.com/102131636/162188480-a64046d5-5ca7-4f4e-ab9f-3a1305dafedd.png)

**Expected result:** 
The text on the banner for ipad view have to be visible properly.

----------------------------------------------------------------------------------------------------------------------------------------
**Retesting :**
**Actual result:**
The text is of black colour and the colour of plate is also of black colour it will overlapp the text.
![image](https://user-images.githubusercontent.com/102131636/162400775-5cf5838d-964e-42f0-91eb-ecaf8e6b1a92.png)
**Expected result:** 
The text of the banner should not overlapp with the plate of the banner used.

**Comment by ui-abhishekkushwaha** [comment]
![MASZL Custom Baskets w_ Bows (3)](https://user-images.githubusercontent.com/95025218/162378299-089afd44-c0d5-4a58-a864-7fe231e99961.png)

**Comment by ui-abhishekkushwaha** [comment]
check this one arrange the text part but about banner left side cutting is looking great there is reason because the the plat is in rounding circle it shows and meaning full the banner

**Comment by sudhanshu0603** [comment]
ok ,removed.
