### ISSUE TITLE
The cross symbol in the product page when we click on the main then the cross symbol is not clicking. 

### ISSUE THREAD

**Issue by sudhanshu0603** [stores-cedcommerce/Internal--Shaka-Store-Built-Redesign---12-April22#25]
**Actual result:**
The cross symbol in the product page when we click on the main then the cross symbol is not clicking. 
https://www.awesomescreenshot.com/video/8286699?key=a5f431c0310270f1d5b939e98bd69f92
**Expected result:**
The cross symbol  have to be clickable.

**Comment by devAlokTripathi** [comment]
@sudhanshu0603 already working please check it once.

**Comment by sudhanshu0603** [comment]
ok , resolved
