### ISSUE TITLE
Some the animation is not coming in full screen in mobile . 

### ISSUE THREAD

**Issue by sudhanshu0603** [stores-cedcommerce/Internal--Shaka-Store-Built-Redesign---12-April22#26]
**Actual result:** 
Some the animation is not coming in full screen in mobile . 
![image](https://user-images.githubusercontent.com/102131636/162192156-7d69e559-3d52-45ac-ae23-921a41e651de.png)
The video issue: https://www.awesomescreenshot.com/video/8301807?key=5a7553f758a03b36129e63056f4e7f36

**Expected result:** 
The animation have to come in full screen it is coming in half screen.

**Comment by ui-abhishekkushwaha** [comment]
Issue solved

**Comment by sudhanshu0603** [comment]
ok, resolved
