### ISSUE TITLE
In search page, double borders are coming on the sortby when we click on it, but in collection page double borders are not coming.

### ISSUE THREAD

**Issue by sudhanshu0603** [stores-cedcommerce/Internal--Shaka-Store-Built-Redesign---12-April22#3]
**Actual result:** 
In search page, double borders are coming on the sortby when we click on it, but in collection page double borders are not coming.
![image](https://user-images.githubusercontent.com/102131636/162149599-60ba5e6b-786d-40cd-8aa0-d8ac8a25ae7b.png)

**Expected result:**
The single border is much better as we have used the pattern of single border.
![image](https://user-images.githubusercontent.com/102131636/162149780-a6aa1f0b-18c1-416a-8312-45cafd0d8df0.png)

**Comment by ui-abhishekkushwaha** [comment]
Issue Solved

**Comment by sudhanshu0603** [comment]
ok, resolved
