### ISSUE TITLE
The buy now button is not coming properly.

### ISSUE THREAD

**Issue by sudhanshu0603** [stores-cedcommerce/Internal--Shaka-Store-Built-Redesign---12-April22#30]
**Actual result:** 
The button is not aligned properly.
![image](https://user-images.githubusercontent.com/102131636/162921683-286483d1-fdb6-433f-960b-4118cdd837e4.png)

**Expected result:**
The button have to be aligned properly.

**Comment by ui-abhishekkushwaha** [comment]
resolve

**Comment by sudhanshu0603** [comment]
ok ,resolved
