### ISSUE TITLE
when making the site live, after filling the email in newsletter then it is shifting to the left side.

### ISSUE THREAD

**Issue by sudhanshu0603** [stores-cedcommerce/Internal--Shaka-Store-Built-Redesign---12-April22#31]
**Actual result:**
when making the site live, after filling the email in newsletter then it is shifting to the left side.
![image](https://user-images.githubusercontent.com/102131636/162941675-0fa33bc6-c6fd-4217-b8b5-6d4b77c4faff.png)

**Expected result:**
The newsletter have to be in fixed position.

**Comment by ui-abhishekkushwaha** [comment]
solved problem

**Comment by sudhanshu0603** [comment]
ok resolved
