### ISSUE TITLE
Search page when we are clicking on the input field da then 4 results are coming but single product is visible.

### ISSUE THREAD

**Issue by sudhanshu0603** [stores-cedcommerce/Internal--Shaka-Store-Built-Redesign---12-April22#32]
**Actual result:**
Search page when we are clicking on the input field da then 4 results are coming but single product is visible.
![image](https://user-images.githubusercontent.com/102131636/162952877-a07e53e2-5bc6-46ba-a28f-f3b70de20f2a.png)

**Expected result:**
The count of the product have to be same as the products are visible after searching.

**Comment by ui-abhishekkushwaha** [comment]
resolve

**Comment by sudhanshu0603** [comment]
ok, resolved
