### ISSUE TITLE
The double borders are coming on the login page.

### ISSUE THREAD

**Issue by sudhanshu0603** [stores-cedcommerce/Internal--Shaka-Store-Built-Redesign---12-April22#33]
**Actual result:**
The double borders are coming on the login page.
![image](https://user-images.githubusercontent.com/102131636/162957458-2f38a642-6874-42c7-b9eb-e2fa4cf128a4.png)

**Expected result:**
The single border have to come in login page.

**Comment by ui-abhishekkushwaha** [comment]
solved problem

**Comment by sudhanshu0603** [comment]
ok, resolved
