### ISSUE TITLE
The header message for forgot password is coming very edge to edge.

### ISSUE THREAD

**Issue by sudhanshu0603** [stores-cedcommerce/Internal--Shaka-Store-Built-Redesign---12-April22#35]
**Actual result:**
The header message for forgot password is coming very edge to edge.
![image](https://user-images.githubusercontent.com/102131636/163099914-7899c5e6-88a3-43a3-8cae-e27a44b47e33.png)

**Expected result:** 
The header message should not be coming edge to edge.

**Comment by ui-abhishekkushwaha** [comment]
problem solve

**Comment by sudhanshu0603** [comment]
ok resolved
