### ISSUE TITLE
The dropdown arrow of search page and collection pages is cropping. 

### ISSUE THREAD

**Issue by sudhanshu0603** [stores-cedcommerce/Internal--Shaka-Store-Built-Redesign---12-April22#37]
**Actual result:**
The dropdown arrow of search page is cropping. 
![image](https://user-images.githubusercontent.com/102131636/163100795-b50cb2da-0c0f-4594-93b7-61164832cc26.png)
**Expected result:**
The relevance dropdown has to be aligned properly.

**Comment by ui-abhishekkushwaha** [comment]
done problem

**Comment by sudhanshu0603** [comment]
ok, resolved
