### ISSUE TITLE
In collection page , when we click on the filter link then the alignment of apply button is not aligned properly.

### ISSUE THREAD

**Issue by sudhanshu0603** [stores-cedcommerce/Internal--Shaka-Store-Built-Redesign---12-April22#38]
**Actual result:**
In collection page , when we click on the filter link then the alignment of apply button is not aligned properly.
![image](https://user-images.githubusercontent.com/102131636/163102108-f0ed5146-c09f-4152-b357-7d9320706a7b.png)

**Expected result:**
The alignment of button have to be proper.

**Comment by ui-abhishekkushwaha** [comment]
resolve

**Comment by sudhanshu0603** [comment]
ok, resolved
