### ISSUE TITLE
Search page the policy pages are coming

### ISSUE THREAD

**Issue by sudhanshu0603** [stores-cedcommerce/Internal--Shaka-Store-Built-Redesign---12-April22#4]
**The url:**
https://maszlcustombaskets.com/search?q=ca&options%5Bprefix%5D=last
**Actual result:**
Some of the policy pages are added in the search page.
![image](https://user-images.githubusercontent.com/102131636/162150678-d3046980-88b8-4d81-b55c-fb6e2581e08a.png)
**Expected result:**
There should not be any policy pages added on the search page.

**Comment by devAlokTripathi** [comment]
@sudhanshu0603  please check it is already fixed.

**Comment by sudhanshu0603** [comment]
ok, resolved
