### ISSUE TITLE
The buttons color have to be of different color , it will be much better

### ISSUE THREAD

**Issue by sudhanshu0603** [stores-cedcommerce/Internal--Shaka-Store-Built-Redesign---12-April22#40]
**Actual result:** 
The buttons color are coming of same color.
![image](https://user-images.githubusercontent.com/102131636/163105647-3cc60628-4f4c-4360-9c26-89999fdb6177.png)
**Expected result:**
The buttons color have to be of different color , it will be much better

**Comment by ui-abhishekkushwaha** [comment]
![image](https://user-images.githubusercontent.com/95025218/163133090-18a31ed1-2db7-4c70-ad18-fde778f564ce.png)
done

**Comment by sudhanshu0603** [comment]
ok, resolved
