### ISSUE TITLE
When we are clicking on more payment option link, then it opening the checkout page. 

### ISSUE THREAD

**Issue by sudhanshu0603** [stores-cedcommerce/Internal--Shaka-Store-Built-Redesign---12-April22#42]
**Actual result:** 
When we are clicking on more payment option link, then it opening the checkout page. 
https://www.awesomescreenshot.com/video/8388832?key=e4b45bd13d149c29ac472588fd9c2e92
**Expected result:**
It have some some options of the payment or buy it now button have to come

**Comment by sudhanshu0603** [comment]
as discussed with the @devAlokTripathi , no need to do, it is fine

**Comment by devAlokTripathi** [comment]
@sudhanshu0603  no need .
