### ISSUE TITLE
Search page after applying price filter the wishlist icon is disappearing.

### ISSUE THREAD

**Issue by sudhanshu0603** [stores-cedcommerce/Internal--Shaka-Store-Built-Redesign---12-April22#5]
**Actual result:** 
Search page after applying price filter the wishlist icon is disappearing.
![image](https://user-images.githubusercontent.com/102131636/162151279-05fcfd7f-f200-4d15-8fd1-51759bc61acb.png)

**Expected result:** 
The wishlist icon have to appear after applying the price

**Comment by devAlokTripathi** [comment]
@sudhanshu0603  please check fixed.
![image](https://user-images.githubusercontent.com/100207984/162332181-dd0b4e0e-6a63-4eb3-a69b-7ea88107ef32.png)
![image](https://user-images.githubusercontent.com/100207984/162332211-f2a5a3ef-3a2c-4fa1-a097-54d84f6111ba.png)

**Comment by sudhanshu0603** [comment]
ok ,resolved
