### ISSUE TITLE
The error message have to be of red colour it will be much better.

### ISSUE THREAD

**Issue by sudhanshu0603** [stores-cedcommerce/Internal--Shaka-Store-Built-Redesign---12-April22#6]
**Actual result:**
The error message have to be of red colour it will be much better.
![image](https://user-images.githubusercontent.com/102131636/162152198-3503ac27-5ba6-431a-abb3-d7f01284f057.png)

**Expected result:**
The error message have to be of red color i will be much better

**Comment by devAlokTripathi** [comment]
@sudhanshu0603 
![image](https://user-images.githubusercontent.com/100207984/162330686-d51bc01a-5067-42b0-9e0e-432e0526d43b.png)

please check

**Comment by sudhanshu0603** [comment]
OK, RESOLVED
