### ISSUE TITLE
Reset password page, the disabled symbol is used when we do not filled the email and hover over the submit button.

### ISSUE THREAD

**Issue by sudhanshu0603** [stores-cedcommerce/Internal--Shaka-Store-Built-Redesign---12-April22#7]
**Actual result:** 
Reset password page, the disabled symbol is used when we do not filled the email and hover over the submit button.
![image](https://user-images.githubusercontent.com/102131636/162162992-7ce152ee-5838-4329-969b-17be02bdcb89.png)

**Expected result:**
The disabled have to used for the submit button as we have used the disabled symbol for all the forms

**Comment by devAlokTripathi** [comment]
@sudhanshu0603  please check 
![image](https://user-images.githubusercontent.com/100207984/162297561-c74f02b2-86e3-42ed-b728-48cdd211de98.png)
fixed.

**Comment by sudhanshu0603** [comment]
ok resolved
