### ISSUE TITLE
After successfull login when we click on the add new address button then it is not clicking. 

### ISSUE THREAD

**Issue by sudhanshu0603** [stores-cedcommerce/Internal--Shaka-Store-Built-Redesign---12-April22#8]
**Actual result:** 
After successfull login when we click on the add new address button then it is not clicking. 
![image](https://user-images.githubusercontent.com/102131636/162164460-504d2262-9c3b-48cd-9288-4e3c36dcdecf.png)

**Expected result:**
The add new address button have to be clickable .

-----------------------------------------------------------------------------------------------------------------------------------------
**RETESTING:** 
**Actual result:** 
The validations are missing for the address page.
![image](https://user-images.githubusercontent.com/102131636/162371312-7e948c83-5bda-40d2-a8ea-cfd9ce39b8df.png)
**Expected result:**
some validation have to be used for the address page, it will be much better.

------------------------------------------------------------------------------------------------------------------------------------------

**After making site live:** 
**Actual result:** 
The edit button delete button  add address button is not working.
![image](https://user-images.githubusercontent.com/102131636/162972736-328d3def-49c0-4529-9221-8c4c89d8f9bb.png)

**Expected :** 
It must be clickable.

**Comment by devAlokTripathi** [comment]
@sudhanshu0603  please check fixed.

**Comment by sudhanshu0603** [comment]
@devAlokTripathi , please review the added point after retesting.

**Comment by devAlokTripathi** [comment]
ok @sudhanshu0603

**Comment by devAlokTripathi** [comment]
@sudhanshu0603  please check  fixed.

**Comment by devAlokTripathi** [comment]
![Uploading image.png…]()

**Comment by sudhanshu0603** [comment]
ok resolved

**Comment by devAlokTripathi** [comment]
https://user-images.githubusercontent.com/100207984/163110871-6db50873-8927-41f3-a3bb-bcc6d80efad9.mp4

@sudhanshu0603  please check button working

**Comment by sudhanshu0603** [comment]
ok resolved
