### ISSUE TITLE
Wishlist page after successful login the wishlist page is overlapping to its header.

### ISSUE THREAD

**Issue by sudhanshu0603** [stores-cedcommerce/Internal--Shaka-Store-Built-Redesign---12-April22#9]
**actual result:**
1: The text of button font are coming very small. EX :addtocart, addalltocart and removeall from wishlist. 
2: header is overlapping
![image](https://user-images.githubusercontent.com/102131636/162371004-51a036ee-c284-45b0-9647-6ff0ff395480.png)

**Expected result:**
The wishlist page have to be visible properly

**Comment by devAlokTripathi** [comment]
@sudhanshu0603  please check 
fixed.

**Comment by sudhanshu0603** [comment]
ok, resolved
